micronaut:
  application:
    name: mysql
datasources:
  default:
    url: jdbc:mysql://containers-us-west-83.railway.app:5984/railway
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'zLL4Ai3vrAITJXJl9d4Y'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true